version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: symfony
      # You should definitely change the password in production
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: symfony
